nodeLinker: node-modules

npmPublishAccess: public

packageExtensions:
  "@algolia/autocomplete-preset-algolia@*":
    peerDependenciesMeta:
      "@algolia/client-search":
        optional: true
  "@docusaurus/theme-common@*":
    peerDependenciesMeta:
      prism-react-renderer:
        optional: true
  "@docusaurus/utils@*":
    peerDependenciesMeta:
      "react":
        optional: true
      "react-dom":
        optional: true
  fork-ts-checker-webpack-plugin@*:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-berry.cjs
