name: Canary Release

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Initialize git configuration
        run: |
          git config --global core.autocrlf false
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Reattach HEAD to head ref
        run: git switch -C "$(echo ${{ github.head_ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
        if: ${{ github.head_ref != '' }}
      - name: Reattach HEAD to ref
        run: git switch -C "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
        if: ${{ github.head_ref == '' }}
      - name: Setup Node environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          architecture: x64
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - name: Installation
        run: |
          npm ci
          rm $(which yarn)
          rm $(which yarnpkg)
      - name: Building work
        run: |
          npm run build
      - name: Publish canary release to NPM registry
        if: startsWith(github.event.head_commit.message, 'chore') == false
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" >> .npmrc
          npm run canary
        env:
          NPM_CONFIG_USERCONFIG: .npmrc
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
