name: Continuous Integration

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Node ${{ matrix.node-version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 16
        architecture:
          - x64
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Initialize git config
        run: |
          git config --global core.autocrlf false
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Reattach HEAD to head ref
        run: git switch -C "$(echo ${{ github.head_ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
        if: ${{ github.head_ref != '' }}
      - name: Reattach HEAD to ref
        run: git switch -C "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
        if: ${{ github.head_ref == '' }}
      - name: Setup Node environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - name: Installation
        run: |
          npm ci
          rm $(which yarn)
          rm $(which yarnpkg)
      - name: Linting
        run: |
          npm run lint --if-present
      - name: E2E testing
        run: |
          npm run e2e --if-present
      - name: Unit testing
        run: |
          npm run test:all --if-present
      - name: Coveralls action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: Node ${{ matrix.node-version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
          base-path: packages/bod
          path-to-lcov: ./packages/bod/coverage/lcov.info
      - name: Building work
        run: |
          npm run build --if-present
      - name: Build documentation
        run: |
          cd website/
          npm ci
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
      - name: Publish to NPM registry
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" >> .npmrc
          npm run publish --if-present
        env:
          NPM_CONFIG_USERCONFIG: .npmrc
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
