name: NPM Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Node ${{ matrix.node-version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 16
        architecture:
          - x64
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
      - name: Setup Node environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - name: Installation
        run: npm ci
      - name: Linting
        run: |
          npm run lint --if-present
      - name: Testing
        run: |
          npm run test --if-present
      - name: Building work
        run: |
          npm run build --if-present
      - name: Publish to NPM
        run: |
          npm run publish --if-present
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
